### ISSUE TITLE
github secret key 추가

### ISSUE THREAD

**Issue by Yoowatney** [mingle-mongle/guzzi#4]
database secret키가 추가되면 좋을듯 합니다
실제 운영 데이터베이스 값보다는 dev branch로 생성한 값이 있으니 요값 넣어보시면 어떨까 싶습니다

[연관 이슈](https://github.com/mingle-mongle/guzzi/actions/runs/5941354831/job/16112015346)

**Comment by mingle-mongle** [comment]
settings -> environment 추가
